# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logview', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(max_length=50)),
                ('comdescription', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
