# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-20 08:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_attention'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attention',
            name='time',
            field=models.CharField(max_length=30),
        ),
    ]
