# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-22 01:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20170120_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='A_Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Attention')),
            ],
        ),
    ]
