# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-22 01:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_a_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='A_Title',
            new_name='ATitle',
        ),
    ]
